### ISSUE TITLE
Warning on Ruby 3.x: `character class has duplicated range`

### ISSUE THREAD

**Issue by nickcampbell18** [yolk/valvat#102]
I'm getting this warning in my CI environment, I'm not entirely sure what it means or if it's a problem, but thought I would report it anyway!

```
~/repo/vendor/bundle/ruby/3.0.0/gems/valvat-1.1.0/lib/valvat/utils.rb:11: warning: character class has duplicated range: /[[:space:][:punct:][:cntrl:]]+/
```

Thanks!

**Comment by yolk** [comment]
Thanks! Warning should be fixed.
