### ISSUE TITLE
Equality for Valvat objects

### ISSUE THREAD

**Issue by ksol** [yolk/valvat#120]
I would like to add a simple check so that it's possible to check Valvat objects for equality. Currently : 

```
Valvat("FR00000000001") == Valvat("FR00000000001")
=> false
```

Is there any objection for this? Any implementation details to consider? (I would have checked if the normalized `@raw` are equal)

In any case, thanks for a pretty great lib !

**Comment by yolk** [comment]
No, no objections from me. Comparing the normalized raw vat-ids seems sensible. Go ahead :)
