### ISSUE TITLE
When do you expect to bump the gem version so we can use updated Cyprus regular expression?

### ISSUE THREAD

**Issue by amerpersonal** [yolk/valvat#126]
Hi,

I saw [this commit](https://github.com/yolk/valvat/commit/41a6e82120617770859ff74339635c33292a6bfe), where new regular expression is introduced for validation Cyprus VAT Number.

We're currently having difficulty with validating number `CY60001744K `

It should be valid. However, it returns it as invalid since validation regex is changed from

````
/\ACY(?!12)[0-59][0-9]{7}[A-Z]\Z/, 
```

to

```
/\ACY(?!12)[0-69][0-9]{7}[A-Z]\Z/, 
```

Regards

**Comment by yolk** [comment]
Thanks for the reminder! I just release v1.4.0 including the changes in #125
