### ISSUE TITLE
Swiss (CH) VAT validation and lookup

### ISSUE THREAD

**Issue by Mollemoll** [yolk/valvat#130]
Hello!

First off, thanks for all the work put into this gem. Big fan!

I'm looking to do Swiss (CH) validations and lookups as well. Would you consider extending Valvat with that functionality?

I have already put some work into it and would be happy to make an effort and open a PR if you'd like.

**Comment by yolk** [comment]
Hi Jonas,

yes, this would be a good addition. But please take a look at the implementation of the UK HMRC Service. I guess I would deactivate the lookup by default and add an `:ch` option, just like the `:uk` one.

Looking forward to your PR!
