### ISSUE TITLE
deprecation of UK VAT number API 1.0 

### ISSUE THREAD

**Issue by Fivell** [yolk/valvat#137]
The Check a UK VAT number API v2.0 is now live. During the following six months, both versions of the Check a UK VAT number API will be available, providing users ample time to migrate. Version 1.0 of the API will be removed by the end of January 2025.

reference https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-registered-companies-api/2.0

**Comment by yolk** [comment]
Closed with v2.0
