### ISSUE TITLE
V2: undefined local variable or method `silence' for an instance of Valvat::Options (NameError)

### ISSUE THREAD

**Issue by jarthod** [yolk/valvat#141]
Hi,

I just tested the v2 to try out this new HMRC API (thanks @Skumring !) but quickly noticed the deprecation warning (for when you keep `uk: true`) is not working as expected:

```ruby
Valvat.new("FR56794011007").exists?(uk: true, detail: true)
(updown):3:in `<main>': undefined local variable or method `silence' for an instance of Valvat::Options (NameError)

      return if @options[:uk] != true || silence
                                         ^^^^^^^
```
That's because the `silence` variable used here is only defined in the `initialize` method (this code was probably moved to another method without re-testing it): https://github.com/yolk/valvat/blob/7bcab78a1a7ef6ad413587ade7c09bd9522eeb13/lib/valvat/options.rb#L36C42-L36C49

Happy holidays :)

**Comment by yolk** [comment]
Hupps. Thanks for the catch... fixed in v2.0.1

Happy holidays!
