### ISSUE TITLE
no possibility to configure savon

### ISSUE THREAD

**Issue by Fivell** [yolk/valvat#39]
Hello, would be great to have possibility to configure internal soap client with open_timeout, read_timeout and other options. Now  when WS is unreachable or sort of it, it takes long time to fail with timeout.

**Comment by yolk** [comment]
Hi,
thanks for your request. This is already possible with the current version:

    Valvat::Lookup.client.globals[:read_timeout] = 5
    Valvat::Lookup.client.globals[:write_timeout] = 5

Thx again,
Sebastian.
