### ISSUE TITLE
getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by mArtinko5MB** [yolk/valvat#48]
Hello, i have just found out that on my production server Valvat is not working for quite some time.

`Valvat.new("SKXXXXXXX").exists?`

turns out to be `nil`

But on my testing server it returns TRUE (which is the right output).

On my production server there is an error message as well

**getaddrinfo: Name or service not known**

> /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:763:in `initialize' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:763:in`open' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:763:in `block in connect' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/timeout.rb:55:in`timeout' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/timeout.rb:100:in `timeout' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:763:in`connect' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:756:in `do_start' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/net/http.rb:745:in`start' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:306:in `open_http' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:775:in`buffer_open' /home/www-data/deploy/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/open-uri.rb:203:in `block in open_loop'

Is it possible that this can be connected to resolve.conf file? (i asked Mr. Google and this is the only explanation i have found)

**Comment by yolk** [comment]
Looks like the VIES-Serverice is not reachable from your server, maybe because you can't resolve the domain name. Could you try to

    curl -v http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl

and

    ping -c 1 ec.europa.eu

and post the output here?

**Comment by mArtinko5MB** [comment]
1. http://pastebin.com/qZJsDEAQ
2. (everytime i get)
> PING ec.europa.eu (147.67.136.103) 56(84) bytes of data.
> 
> --- ec.europa.eu ping statistics ---
> 1 packets transmitted, 0 received, 100% packet loss, time 0ms

But it seems to be working at the moment, it's weird


`

**Comment by yolk** [comment]
Weired indeed.

Could you run

    ping ec.europa.eu

for a while to check if your connection is not stable? 

Doesn't seem to be valvat related.

**Comment by mArtinko5MB** [comment]
> PING ec.europa.eu (147.67.136.21) 56(84) bytes of data.
> ^C
> --- ec.europa.eu ping statistics ---
> 242 packets transmitted, 0 received, 100% packet loss, time 241536ms
> 
>

**Comment by yolk** [comment]
Sorry. Ignore the ping results. Doesn't work for me either. But with the curl request succeeding and valvat working on your production server it seems like the (DNS?) issue resolved itself. Maybe you could repeat the curl test if it is failing again?

**Comment by mArtinko5MB** [comment]
I'll let you know
