### ISSUE TITLE
0.8.2 has breaking changes

### ISSUE THREAD

**Issue by henrik** [yolk/valvat#69]
Hi!

I know a pre-1.0 lib doesn't strictly need to follow any conventions as far as semver is concerned, but I noticed that tests failed after upgrading to 0.8.2, since it made previously invalid numbers valid (because it normalises them).

So if you want to be semver-like with this lib, maybe that should be a major change (1.0.0?) or at least a minor one (0.9.0) if you want to only consider this a new feature.

We upgrade libs daily and rely on version numbers to get a rough idea about risk of breakage – I didn't assume a tiny upgrade would break specs :)

**Comment by yolk** [comment]
First, let me be clear: This wasn't my intention: The changes discussed in https://github.com/yolk/valvat/pull/64 shouldn't break any tests. Could you maybe give a example of a VAT id that broke with the new normalization regexp?

Thanks and sorry for the hassle!

**Comment by henrik** [comment]
Hi! No worries :)

This spec failed for us:

```
it "disallows values with the wrong format for the EU" do
  company.vat_number = "GB999/9999/99"
  expect(company.errors_on(:vat_number).length).to eq(1)
end
```

Definitely not a big deal, and an easy fix for us. Just thought I'd mention it :)

**Comment by yolk** [comment]
I guess the change could be interpreted as an fix: the initial intention of the regexp used to normalize the input was to remove any whitespace and punctation chars. But it didn't include the forward slash; which – as demonstrated in your spec – could be used to divide the parts of an VAT id.

I know this is a little bit on the edge. I promise to stick more strictly to semver in the future... a first step would be to finally release an v1.0 :-)

**Comment by henrik** [comment]
Hehe, yeah, 1.0 is scary :D Sounds good! Thanks for the quick response!
