### ISSUE TITLE
Testing with VCR doesn't work

### ISSUE THREAD

**Issue by svobom57** [yolk/valvat#75]
There seems to be an issue caused by this line:
https://github.com/yolk/valvat/blob/f44aca5b0e3559b1150e9d1ddcffce0300a08796/lib/valvat/lookup.rb#L20

When we tried writing specs we were expecting our RSpec environment to complain about uncaught VCR request to VIES API but we've got none.

The VCR error is caught in the rescue all exception block. I think that's not the desired behaviour and we should probably be catching just the `Savon` errors rather than all `StandardErrors`.

**Comment by yolk** [comment]
Hi Chris,

the current master branch includes (not yet released)  changes that only rescue expected errors, and should allow the usage of VCR. Could you give it a try?

Hope this helps.

Thanks,
Sebastian.

**Comment by svobom57** [comment]
I don't have access to the codebase I worked on anymore. But looking at master, this should solve the issue and now an error should be raised in VCR whenever the API call is attempted.

I reckon this can be closed once the `master` branch is released. Thanks!

**Comment by yolk** [comment]
Thanks a lot for checking!

**Comment by yolk** [comment]
Just released version 1.0.0 includes this fix.
