### ISSUE TITLE
Debugging option?

### ISSUE THREAD

**Issue by lubekpl** [yolk/valvat#78]
We've seeing a lot of `nil` responses lately from consecutive requests to VIES
Something along the lines
```
2020-05-06 08:46:10 Existance check returned true on VAT #######
2020-05-06 08:46:13 Existance check returned nil on VAT #######
```
is there an option to debug what exactly is happening? maybe VIES is throttling us?

**Comment by yolk** [comment]
Hi Chris,

the current master branch includes (not yet released)  changes that should throw an `Valvat::RateLimitError` if you are throttled. Could you give it a try and report the results?

Hope this helps.

Thanks,
Sebastian.

**Comment by lubekpl** [comment]
Started using 
```
    valvat_instance.exists?(
      requester_vat: LF_VAT_ID,
      raise_error: true
    )
```

and works like a charm, can catch the error, log and retry :+1:
