### ISSUE TITLE
Valvat::Checksum.validate returns an exception for some invalid VAT numbers

### ISSUE THREAD

**Issue by kantyka** [yolk/valvat#81]
Since version 0.8.0 checksum validation returns an exception for some Irish VAT numbers. 
This happens for numbers that end with a character that is not in CHARS constant like X or Y.

Steps to reproduce:
Install valvat >= 0.8.0 and execute
```
vat = 'IE0000000AZ'
Valvat::Checksum.validate(vat)
```

Expected result:
```
false
```

Actual result: 
```
NoMethodError: undefined method `*' for nil:NilClass
```

This breaks validation in our form for some values provided by users.

**Comment by arekk** [comment]
Another one: `Valvat::Checksum.validate('IE0000000XX')`

**Comment by yolk** [comment]
Thanks arekk! I just added a simple fix. Maybe you could test it with some irish vat numbers?

**Comment by yolk** [comment]
And thanks @kantyka ! Sorry, I mixed up the names.

**Comment by kantyka** [comment]
Thank you for your quick response. 
I have tested your fix with 500 Irish numbers, both real and fake and it works correctly.

**Comment by yolk** [comment]
Wow. Thanks a lot for the extensive test!
