### ISSUE TITLE
Getting Nil in all validate cases

### ISSUE THREAD

**Issue by avschiller** [yolk/valvat#82]
Since this change (https://github.com/yolk/valvat/pull/76) on April 17 my service has been getting nil responses from validate/exists requests. I'm getting the same nil responses described in this issue https://github.com/yolk/valvat/issues/73, but only after the https change. Are you aware of any issues this change could have caused? 

I tried debugging by sending options to override the savon wsdl to the old http value, but still get nil results:
```
irb(main):022:0> Valvat.new("BG123123123").exists?
=> nil
irb(main):023:0> Valvat::Lookup.validate("DE100")
=> nil
irb(main):024:0> option_http = {savon: {wsdl: "http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl"}}
=> {:savon=>{:wsdl=>"http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl"}}
irb(main):025:0> Valvat.new("BG123123123").exists?(option_http)
=> nil
irb(main):026:0> Valvat::Lookup.validate("DE100", option_http)
=> nil
```

**Comment by avschiller** [comment]
More info on the gems my project is using.
```
gem 'valvat', '0.4.7'
gem 'savon', '1.2.0'
```
Validate works when i test with these upgraded gems: 
```
gem 'valvat', '0.9.1'
gem 'savon', '2.12.0'
```
I'd prefer to not upgrade my codebase to savon 2. Is validation expected to work on valvat 0.4.7?

**Comment by lubekpl** [comment]
I'm sorry if I misunderstand but you're using 0.4.7 in your project?

If so, that's expected - VIES changed the url (they've added SSL) and the original url (http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl) ends up redirecting. 

```
❯ curl http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl
<HTML><HEAD>
<TITLE>Redirect</TITLE>
</HEAD>
<BODY>
# unimportant stuff
Click <a href="https:&#x2F;&#x2F;ec.europa.eu&#x2F;taxation_customs&#x2F;vies&#x2F;checkVatService.wsdl">here</a> if you are not automatically redirected.
</FONT>
# unimportant stuff
</BODY></HTML>
```

There were two changes made to Valvat regarding the issue, both of which you mention in your original post, first [here](https://github.com/yolk/valvat/pull/74) to follow redirects, the second one [here](https://github.com/yolk/valvat/pull/76) that actually changes the url.

I'd suggest either upgrading Valvat or you could monkeypatch the wsdl url in your app.

**Comment by avschiller** [comment]
Okay, thanks for your explanation!
