### ISSUE TITLE
How to test errors?

### ISSUE THREAD

**Issue by timokleemann** [yolk/valvat#90]
First of all: Thanks for the great plugin! I've been using it for months now on my [invoicing platform](https://www.billingengine.com). Without any troubles.

Today I ran into an error for the very first time: `Valvat::RateLimitError` (I don't know what it means or why it occurred.)

Is there a way to _fake_ this type of error (or any other Valvat error) to alleviate testing and handling of these errors?

Thanks for your help.

**Comment by yolk** [comment]
Hi there!

`Valvat::RateLimitError` means you hit the VIES-API (or some of the underlying national APIs) with to many requests to fast, broke their rate limit, and should slow the pace of requests down. I guess they limit you based on your IP-Address.

Regarding the testing of such errors, I would recommend to study the documentation of your testing framework. In Rspec you could simply use a stub:

`Valvat::Lockup.stub(:validate).and_raise(Valvat::RateLimitError.new)`
