### ISSUE TITLE
Portuguese translation failing due to missing space on locale yml file

### ISSUE THREAD

**Issue by JosimarCamargo** [yolk/valvat#93]
First of all thanks for your awesome work!

I think the missing spaces after the key `country_adjectives` is the probably cause to the translation of country_adjectives to fail
I identify in the portuguese language.
https://github.com/yolk/valvat/blob/f811986d4548e0e2981d45793d226ac650c1dfd9/lib/valvat/locales/pt.yml#L7

I could fix overwriting the locale file on my application.

I think in a few days if anyone opens a PR to fix, I can try read the project guidelines and open the PR.

Thanks for the great work, stay safe!

**Comment by yolk** [comment]
Thanks a lot @JosimarCamargo ... I fixed it right away!
